
FROM python:3.11


WORKDIR /pytss

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

# CMD ["python", "./app/main.py"]
CMD ["streamlit", "run", "app.py", "--server.address", "0.0.0.0", "--server.port", "8080"]